package cmd

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"

	"github.com/scoopinstaller/scoop-go/pkg/app"
	"github.com/scoopinstaller/scoop-go/pkg/bucket"
	"github.com/scoopinstaller/scoop-go/pkg/install"
	"github.com/spf13/cobra"
)

var importCmd = &cobra.Command{
	Use:   "import <path>",
	Short: "Imports apps, buckets and configs from a Scoopfile in JSON format",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		path := args[0]

		data, err := readScoopfileData(path)
		if err != nil {
			return fmt.Errorf("reading import file: %w", err)
		}

		// Accept both PowerShell export (Name/Source/Info) and Go export (name/source/global).
		var scoopfile struct {
			Buckets []json.RawMessage   `json:"buckets"`
			Apps    []json.RawMessage   `json:"apps"`
			Config  map[string]interface{} `json:"config,omitempty"`
		}
		if err := json.Unmarshal(data, &scoopfile); err != nil {
			return fmt.Errorf("parsing scoopfile: %w", err)
		}

		// Config first (matches PowerShell import order)
		if len(scoopfile.Config) > 0 {
			cfg := app.Config()
			for k, v := range scoopfile.Config {
				if err := cfg.Set(k, v); err != nil {
					app.LogWarn("setting config '%s': %v", k, err)
					continue
				}
				app.LogInfo("'%s' has been set", k)
			}
			if err := cfg.Save(); err != nil {
				app.LogWarn("saving config: %v", err)
			}
		}

		var bucketNames []string
		for _, raw := range scoopfile.Buckets {
			b := parseImportBucket(raw)
			if b.Name == "" {
				continue
			}
			bucketNames = append(bucketNames, b.Name)
			if bucket.IsLocal(b.Name) {
				app.LogInfo("Bucket '%s' already exists, skipping.", b.Name)
				continue
			}
			repo := b.Source
			if repo == "" {
				if r, ok := bucket.Repo(b.Name); ok {
					repo = r
				} else {
					app.LogWarn("Unknown bucket '%s', skipping.", b.Name)
					continue
				}
			}
			if err := bucket.Add(b.Name, repo); err != nil {
				app.LogWarn("Adding bucket '%s': %v", b.Name, err)
			}
		}

		defArch := install.GetArchitecture("")
		for _, raw := range scoopfile.Apps {
			a := parseImportApp(raw)
			if a.Name == "" {
				continue
			}

			global := a.Global || strings.Contains(a.Info, "Global install")
			hold := strings.Contains(a.Info, "Held package")
			arch := defArch
			for _, candidate := range []string{"64bit", "32bit", "arm64"} {
				if strings.Contains(a.Info, candidate) {
					arch = candidate
					break
				}
			}

			// Resolve install ref like PowerShell import
			installRef := a.Name
			if a.Source != "" {
				if containsString(bucketNames, a.Source) || bucket.IsLocal(a.Source) {
					installRef = a.Source + "/" + a.Name
				} else if a.Source == "<auto-generated>" && a.Version != "" {
					installRef = a.Name + "@" + a.Version
				} else if strings.HasPrefix(a.Source, "http://") || strings.HasPrefix(a.Source, "https://") {
					installRef = a.Source
				}
			}

			appName, bucketName, version := parseAppRef(installRef)
			if appName == "" {
				appName = a.Name
			}
			if version == "" {
				version = a.Version
			}

			app.LogInfo("Installing '%s'...", appName)
			m, foundBucket, err := install.FindManifest(appName)
			if err != nil {
				// URL install path
				if strings.HasPrefix(installRef, "http://") || strings.HasPrefix(installRef, "https://") {
					app.LogWarn("URL import for '%s' not fully supported yet: %v", appName, err)
				} else {
					app.LogWarn("Finding manifest for '%s': %v", appName, err)
				}
				continue
			}
			if bucketName != "" {
				foundBucket = bucketName
			}

			versionToInstall := m.Version
			if version != "" && version != m.Version {
				m, err = install.GenerateVersionManifest(context.Background(), appName, m, version, arch, true)
				if err != nil {
					app.LogWarn("Generating version manifest for '%s@%s': %v", appName, version, err)
					continue
				}
				versionToInstall = version
			}

			engine := &install.Engine{
				AppName:   appName,
				Manifest:  m,
				Bucket:    foundBucket,
				Version:   versionToInstall,
				Arch:      arch,
				Global:    global,
				UseCache:  true,
				CheckHash: true,
			}
			if err := engine.Install(context.Background()); err != nil {
				if _, ok := err.(*install.AlreadyInstalledError); ok {
					app.LogInfo("'%s' is already installed.", appName)
				} else {
					app.LogWarn("Installing '%s': %v", appName, err)
					continue
				}
			}

			if hold {
				if err := setHold(appName, true, global); err != nil {
					app.LogWarn("Holding '%s': %v", appName, err)
				}
			}
		}

		app.LogSuccess("Import completed.")
		return nil
	},
}

type importBucket struct {
	Name   string
	Source string
}

type importApp struct {
	Name    string
	Version string
	Source  string
	Info    string
	Global  bool
}

func parseImportBucket(raw json.RawMessage) importBucket {
	var m map[string]interface{}
	if json.Unmarshal(raw, &m) != nil {
		return importBucket{}
	}
	return importBucket{
		Name:   firstString(m, "Name", "name"),
		Source: firstString(m, "Source", "source"),
	}
}

func parseImportApp(raw json.RawMessage) importApp {
	var m map[string]interface{}
	if json.Unmarshal(raw, &m) != nil {
		return importApp{}
	}
	a := importApp{
		Name:    firstString(m, "Name", "name"),
		Version: firstString(m, "Version", "version"),
		Source:  firstString(m, "Source", "source"),
		Info:    firstString(m, "Info", "info"),
	}
	if g, ok := m["global"].(bool); ok {
		a.Global = g
	}
	if g, ok := m["Global"].(bool); ok {
		a.Global = g
	}
	return a
}

func firstString(m map[string]interface{}, keys ...string) string {
	for _, k := range keys {
		if v, ok := m[k]; ok {
			switch t := v.(type) {
			case string:
				return t
			default:
				return fmt.Sprint(t)
			}
		}
	}
	return ""
}

func containsString(list []string, s string) bool {
	for _, x := range list {
		if x == s {
			return true
		}
	}
	return false
}

func readScoopfileData(path string) ([]byte, error) {
	if strings.HasPrefix(path, "http://") || strings.HasPrefix(path, "https://") {
		resp, err := http.Get(path)
		if err != nil {
			return nil, fmt.Errorf("downloading scoopfile: %w", err)
		}
		defer resp.Body.Close()
		return io.ReadAll(resp.Body)
	}
	return os.ReadFile(path)
}

func init() {
	rootCmd.AddCommand(importCmd)
}
